// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QRCodeEvidentationApp.Data;

#nullable disable

namespace QRCodeEvidentationApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240625101226_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinkiEvidentationProject.Models.AuthUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuthUsers");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssistantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Assistants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("English")
                        .HasColumnType("bit");

                    b.Property<float?>("GroupPortion")
                        .HasColumnType("real");

                    b.Property<string>("Groups")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinedSubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastNameRegex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfFirstEnrollments")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfReEnrollments")
                        .HasColumnType("int");

                    b.Property<string>("ProfessorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Professors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemesterCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<short?>("StudyYear")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.HasIndex("JoinedSubjectId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("SemesterCode");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.CourseProfessorEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint");

                    b.Property<string>("ProfessorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("CourseProfessorEvaluations");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.CourseStudentGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentGroupsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentGroupsId");

                    b.ToTable("CourseStudentGroups");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.JoinedSubject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Codes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cycle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemesterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValidationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeeklyAuditoriumClasses")
                        .HasColumnType("int");

                    b.Property<int?>("WeeklyLabClasses")
                        .HasColumnType("int");

                    b.Property<int?>("WeeklyLecturesClasses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("JoinedSubjects");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Lecture", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfessorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("RoomName");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.LectureAttendance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EvidentedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LectureId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIndex1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LectureId");

                    b.HasIndex("StudentIndex1");

                    b.ToTable("LectureAttendances");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.LectureCourses", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<string>("LectureId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LectureId");

                    b.ToTable("LectureCourses");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Professor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("OrderingRank")
                        .HasColumnType("smallint");

                    b.Property<string>("RoomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.ProfessorDetail", b =>
                {
                    b.Property<string>("ProfessorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("BirthDay")
                        .HasColumnType("date");

                    b.Property<string>("CurrentTitleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegreeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Order")
                        .HasColumnType("float");

                    b.HasKey("ProfessorId");

                    b.ToTable("ProfessorDetails");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Room", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("Capacity")
                        .HasColumnType("bigint");

                    b.Property<string>("EquipmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Semester", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EnrollmentEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EnrollmentStartDate")
                        .HasColumnType("date");

                    b.Property<string>("SemesterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Student", b =>
                {
                    b.Property<string>("StudentIndex")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyProgramCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentIndex");

                    b.HasIndex("StudyProgramCode");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudentCourse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<string>("StudentStudentIndex")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentStudentIndex");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudentGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("English")
                        .HasColumnType("bit");

                    b.Property<string>("LastNameRegex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Programs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemesterCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<short?>("StudyYear")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SemesterCode");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudentSubjectEnrollment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Assistants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvalidNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinedSubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<short?>("NumEnrollments")
                        .HasColumnType("smallint");

                    b.Property<string>("ProfessorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Professors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemesterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("StudentGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("StudentStudentIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("JoinedSubjectId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("SemesterCode");

                    b.HasIndex("StudentGroupId");

                    b.HasIndex("StudentStudentIndex");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjectEnrollments");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudyProgram", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("StudyPrograms");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudyProgramSubject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DependenciesOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Mandatory")
                        .HasColumnType("bit");

                    b.Property<double?>("Order")
                        .HasColumnType("float");

                    b.Property<short?>("Semester")
                        .HasColumnType("smallint");

                    b.Property<string>("StudyProgramCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectDetailSubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudyProgramCode");

                    b.HasIndex("SubjectDetailSubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudyProgramSubjects");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudyProgramSubjectProfessor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Order")
                        .HasColumnType("float");

                    b.Property<string>("ProfessorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudyProgramSubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("StudyProgramSubjectId");

                    b.ToTable("StudyProgramSubjectProfessors");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeeklyAuditoriumClasses")
                        .HasColumnType("int");

                    b.Property<int?>("WeeklyLabClasses")
                        .HasColumnType("int");

                    b.Property<int?>("WeeklyLecturesClasses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.SubjectDetail", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccreditationYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ActivityPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CopyOfSubjectDetailsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Credits")
                        .HasColumnType("real");

                    b.Property<string>("Cycle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("DefaultSemester")
                        .HasColumnType("smallint");

                    b.Property<string>("Dependencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependencyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ExamPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("ExerciseHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalsDescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeworkHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearningMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LectureHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Placeholder")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ProjectPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("QualityControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelfLearningHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("TestsPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("TotalHours")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("SubjectDetails");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.SubjectNameMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubjectNameMappings");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.TeacherSubject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ProfessorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Course", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Professor", "Assistant")
                        .WithMany("CourseAssistants")
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinkiEvidentationProject.Models.JoinedSubject", "JoinedSubject")
                        .WithMany("Courses")
                        .HasForeignKey("JoinedSubjectId");

                    b.HasOne("FinkiEvidentationProject.Models.Professor", "Professor")
                        .WithMany("CourseProfessors")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinkiEvidentationProject.Models.Semester", "Semester")
                        .WithMany("Courses")
                        .HasForeignKey("SemesterCode");

                    b.Navigation("Assistant");

                    b.Navigation("JoinedSubject");

                    b.Navigation("Professor");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.CourseProfessorEvaluation", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Course", "Course")
                        .WithMany("CourseProfessorEvaluations")
                        .HasForeignKey("CourseId");

                    b.HasOne("FinkiEvidentationProject.Models.Professor", "Professor")
                        .WithMany("CourseProfessorEvaluations")
                        .HasForeignKey("ProfessorId");

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.CourseStudentGroup", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinkiEvidentationProject.Models.StudentGroup", "StudentGroups")
                        .WithMany()
                        .HasForeignKey("StudentGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.JoinedSubject", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Subject", "Subject")
                        .WithMany("JoinedSubjects")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Lecture", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinkiEvidentationProject.Models.Room", "Room")
                        .WithMany("Lectures")
                        .HasForeignKey("RoomName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.LectureAttendance", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Lecture", "Lecture")
                        .WithMany()
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinkiEvidentationProject.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentIndex1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.LectureCourses", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinkiEvidentationProject.Models.Lecture", "Lecture")
                        .WithMany("Courses")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.ProfessorDetail", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Professor", "Professor")
                        .WithOne("ProfessorDetail")
                        .HasForeignKey("FinkiEvidentationProject.Models.ProfessorDetail", "ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Student", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.StudyProgram", "StudyProgramCodeNavigation")
                        .WithMany("Students")
                        .HasForeignKey("StudyProgramCode");

                    b.Navigation("StudyProgramCodeNavigation");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudentCourse", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId");

                    b.HasOne("FinkiEvidentationProject.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentStudentIndex");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudentGroup", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Semester", "SemesterCodeNavigation")
                        .WithMany("StudentGroups")
                        .HasForeignKey("SemesterCode");

                    b.Navigation("SemesterCodeNavigation");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudentSubjectEnrollment", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Course", "Course")
                        .WithMany("StudentSubjectEnrollments")
                        .HasForeignKey("CourseId");

                    b.HasOne("FinkiEvidentationProject.Models.JoinedSubject", "JoinedSubject")
                        .WithMany("StudentSubjectEnrollments")
                        .HasForeignKey("JoinedSubjectId");

                    b.HasOne("FinkiEvidentationProject.Models.Professor", "Professor")
                        .WithMany("StudentSubjectEnrollments")
                        .HasForeignKey("ProfessorId");

                    b.HasOne("FinkiEvidentationProject.Models.Semester", "Semester")
                        .WithMany("StudentSubjectEnrollments")
                        .HasForeignKey("SemesterCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinkiEvidentationProject.Models.StudentGroup", "StudentGroup")
                        .WithMany("StudentSubjectEnrollments")
                        .HasForeignKey("StudentGroupId");

                    b.HasOne("FinkiEvidentationProject.Models.Student", "Student")
                        .WithMany("StudentSubjectEnrollments")
                        .HasForeignKey("StudentStudentIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinkiEvidentationProject.Models.Subject", "Subject")
                        .WithMany("StudentSubjectEnrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("JoinedSubject");

                    b.Navigation("Professor");

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("StudentGroup");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudyProgramSubject", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.StudyProgram", "StudyProgramCodeNavigation")
                        .WithMany("StudyProgramSubjects")
                        .HasForeignKey("StudyProgramCode");

                    b.HasOne("FinkiEvidentationProject.Models.SubjectDetail", "SubjectDetail")
                        .WithMany("StudyProgramSubjects")
                        .HasForeignKey("SubjectDetailSubjectId");

                    b.HasOne("FinkiEvidentationProject.Models.Subject", "Subject")
                        .WithMany("StudyProgramSubjects")
                        .HasForeignKey("SubjectId");

                    b.Navigation("StudyProgramCodeNavigation");

                    b.Navigation("Subject");

                    b.Navigation("SubjectDetail");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudyProgramSubjectProfessor", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Professor", "Professor")
                        .WithMany("StudyProgramSubjectProfessors")
                        .HasForeignKey("ProfessorId");

                    b.HasOne("FinkiEvidentationProject.Models.StudyProgramSubject", "StudyProgramSubject")
                        .WithMany("StudyProgramSubjectProfessors")
                        .HasForeignKey("StudyProgramSubjectId");

                    b.Navigation("Professor");

                    b.Navigation("StudyProgramSubject");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.SubjectDetail", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Subject", "Subject")
                        .WithOne("SubjectDetail")
                        .HasForeignKey("FinkiEvidentationProject.Models.SubjectDetail", "SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.TeacherSubject", b =>
                {
                    b.HasOne("FinkiEvidentationProject.Models.Professor", "Professor")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("ProfessorId");

                    b.HasOne("FinkiEvidentationProject.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Professor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Course", b =>
                {
                    b.Navigation("CourseProfessorEvaluations");

                    b.Navigation("StudentCourses");

                    b.Navigation("StudentSubjectEnrollments");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.JoinedSubject", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("StudentSubjectEnrollments");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Lecture", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Professor", b =>
                {
                    b.Navigation("CourseAssistants");

                    b.Navigation("CourseProfessorEvaluations");

                    b.Navigation("CourseProfessors");

                    b.Navigation("ProfessorDetail");

                    b.Navigation("StudentSubjectEnrollments");

                    b.Navigation("StudyProgramSubjectProfessors");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Room", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Semester", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("StudentGroups");

                    b.Navigation("StudentSubjectEnrollments");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Student", b =>
                {
                    b.Navigation("StudentCourses");

                    b.Navigation("StudentSubjectEnrollments");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudentGroup", b =>
                {
                    b.Navigation("StudentSubjectEnrollments");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudyProgram", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("StudyProgramSubjects");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.StudyProgramSubject", b =>
                {
                    b.Navigation("StudyProgramSubjectProfessors");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.Subject", b =>
                {
                    b.Navigation("JoinedSubjects");

                    b.Navigation("StudentSubjectEnrollments");

                    b.Navigation("StudyProgramSubjects");

                    b.Navigation("SubjectDetail");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("FinkiEvidentationProject.Models.SubjectDetail", b =>
                {
                    b.Navigation("StudyProgramSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
